config/routes.rb
# -*- encoding : utf-8 -*-
Nacer::Application.routes.draw do

  resources :notificaciones
  put 'notificaciones/:id/edit', to: "notificaciones#update"

  scope '/(:locale)', defaults: { locale: 'es' }, constraints: { locale: /es|en/ } do
    authenticated :user, -> user { user.in_group? [:administradores,:facturacion]} do
      mount Delayed::Web::Engine => '/jobs'
    end
  end
  
  resources :procesos_de_sistemas , :only => [:index,:destroy,:show] 

  get "datos_reportables/show"
  get "prestaciones/autorizadas"
  get "diagnosticos/por_prestacion"

  # Informes de rendicion
  resources :informes_de_rendicion
  put 'informes_de_rendicion/:id/edit', to: "informes_de_rendicion#update"
  post 'informes_de_rendicion/new', to: "informes_de_rendicion#create"
  get 'informes_de_rendicion/index'

  resources :documentos_generables
  resources :notas_de_debito
  resources :prestaciones_principales

  resources :informes_debitos_prestacionales do
    resources :detalles_de_debitos_prestacionales, only: [:index, :create, :destroy]
    put :iniciar, on: :member
    put :finalizar, on: :member
    put :cerrar, on: :member
  end

  resources :expedientes_sumar do
    get 'generar_caratulas_expedientes_por_liquidacion', as: :generar_caratulas_expedientes_por_liquidacion, action: :generar_caratulas_expedientes_por_liquidacion, on: :member
  end

  get "documentos_electronicos/index"
  get "capacitaciones/index"

  get 'buscar_prestacion_liquidada/:action' => 'prestaciones_liquidadas#:action'
  get 'buscar_prestacion_liquidada/por_afiliado_concepto_y_efector' => 'prestaciones_liquidadas#por_afiliado_concepto_y_efector', as: :prestaciones_liquidadas_por_afiliado_efector_concepto

  #Liquidaciones - Sumar
  resources :conceptos_de_facturacion do
    resources :documentos_generables_por_conceptos, only: [:index, :create, :destroy]
  end
  resources :periodos
  resources :tipos_periodos
  resources :formulas
  resources :grupos_de_efectores_liquidaciones

  resources :liquidaciones_sumar do
    get '/efectores/:id', to: 'liquidaciones_sumar#detalle_de_prestaciones_liquidadas_por_efector', as: 'detalle_de_prestaciones_liquidadas_por_efector'
    member do
      post   'procesar_liquidaciones',  as: :procesar_liquidaciones, action: :procesar_liquidaciones
      post   'procesar_liquidacion', as: :procesar_liquidacion, action: :procesar_liquidacion
      post   'generar_cuasifacturas', as: :generar_cuasifacturas, action: :generar_cuasifacturas
      delete 'vaciar_liquidacion', :as => :vaciar_liquidacion, :action => :vaciar_liquidacion
    end
  end
  
  resources :solicitudes_addendas do
    member do
         post   'confirmar_solicitud', as: :confirmar_solicitud, action: :confirmar_solicitud
         post   'aprobacion_tecnica' , as: :aprobacion_tecnica, action: :aprobacion_tecnica
         post   'aprobacion_legal'   , as: :aprobacion_legal, action: :aprobacion_legal
         post   'anular_solicitud'   , as: :anular_solicitud, action: :anular_solicitud
    end
  end
  
  
  resources :reglas
  resources :liquidaciones_sumar_anexos_administrativos do
    put :finalizar_anexo, on: :member
  end
  resources :liquidaciones_sumar_anexos_medicos do
    put :finalizar_anexo, on: :member
  end
  resources :plantillas_de_reglas
  # resources :liquidaciones_sumar_cuasifacturas_detalles
  resources :liquidaciones_sumar_cuasifacturas
  resources :parametros_liquidaciones_sumar
  resources :liquidaciones_informes do
    member do
      post 'cerrar', as: :cerrar, action: :cerrar
    end
  end

  resources :secciones_pdss, only: [] do
    resources :grupos_pdss, only: :index
  end

  resources :grupos_pdss, only: [] do
    resources :grupos_poblacionales, only: :index
    resources :sexos, only: :index
  end

  resources :consolidados_sumar
  # rutas para la actualizacion asincronica
  resources :anexos_medicos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end
  resources :anexos_administrativos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end

  resources :datos_reportables , :only => :show

  devise_for :users, :controllers => { :sessions => "user_sessions", :registrations => "users", :passwords => "passwords" }
  devise_scope :user do
    get "users", :to => "users#index", :as => :users
    get "users/:id", :to => "users#admin_edit", :as => :user
    get "users/:id/edit", :to => "users#admin_edit", :as => :edit_user
    put "users/:id", :to => "users#admin_update"
    get "seleccionar_uad" => "user_sessions#seleccionar_uad", :as => :seleccionar_uad
    delete "users/:id", :to => "users#destroy", :as => :delete_user
  end
  resources :convenios_de_administracion, :except => :destroy
  resources :convenios_de_gestion, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
  end
  resources :convenios_de_administracion_sumar, :except => :destroy
  resources :convenios_de_gestion_sumar, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
    get 'firmante', :on => :member
  end
  resources :efectores, :except => :destroy do
    get 'prestaciones_autorizadas', :on => :member, :as => :prestaciones_autorizadas_del
    get 'referentes', :on => :member, :as => :referentes_del
  end
  resources :paises, :except => :destroy
  resources :provincias, :except => :destroy
  resources :departamentos, :except => :destroy
  resources :distritos, :except => :destroy
  resources :informes, :except => :destroy do
    get "informe_solicitado", on: :collection, as: :render_informe_default, action: :render_informe
  end
  resources :addendas, :except => :destroy
  resources :addendas_sumar, :except => :destroy do
    get 'new_masivo', :on => :collection, :as => :new_masivo
    post 'create_masivo', :on => :collection, :as => :create_masivo
  end
  resources :nomencladores, :except => :destroy do
    get 'asignar_precios', :on => :member, :as => :new_asignar_precios, :action => :new_asignar_precios
    get 'grupo_pdss/:grupo_pdss_id/asignar_precios', :on => :member, :as => :new_asignar_precios_por_grupo_pdss, :action => :new_asignar_precios_por_grupo_pdss
    put 'update_asignar_precios', :on => :member, :as => :update_asignar_precios, :action => :update_asignar_precios
  end
  resources :busqueda, :only => :index
  resources :verificador, :only => :index
  resources :padrones, :only => :index do
    post 'cierre', :on => :collection, :as => :cierre_de
  end
  resources :referentes, :except => [:index, :show, :destroy]
  resources :contactos#, :except => :destroy
  resources :liquidaciones, :except => :destroy
  resources :cuasi_facturas, :except => :destroy
  match "importar_detalle" => "cuasi_facturas#importar_detalle"
  match "importar_registros_de_prestaciones" => "cuasi_facturas#importar_registros_de_prestaciones"
  match "importar_archivo_p" => "liquidaciones#importar_archivo_p"
  match "procesar_bajas" => "novedades_de_los_afiliados#procesar_bajas"
  resources :novedades_de_los_afiliados, :except => [:new, :create] do
    get 'alta', :on => :collection, :as => :new_alta, :action => :new_alta
    get 'baja', :on => :collection, :as => :new_baja, :action => :new_baja
    get 'modificacion', :on => :collection, :as => :new_modificacion, :action => :new_modificacion
    post 'alta', :on => :collection, :as => :create_alta, :action => :create_alta
    post 'baja', :on => :collection, :as => :create_baja, :action => :create_baja
    post 'modificacion', :on => :collection, :as => :create_modificacion, :action => :create_modificacion
  end
  resources :afiliados, :only => [:show] do
    get :busqueda_por_aproximacion, on: :collection
    get 'prestaciones_brindadas', :on => :member, :as => :prestaciones_brindadas_al
  end
  resources :unidades_de_alta_de_datos, :except => :destroy
  resources :prestaciones_brindadas
  match "informe_de_beneficiarios_activos" => "informes#beneficiarios_activos"
  match "tablero_de_comandos_alto_impacto" => "informes#tablero_de_comandos_alto_impacto"
  resources :procesos_de_datos_externos, :except => :destroy do
    member do
      post 'aplicar', :as => :aplicar, :action => :aplicar
      post 'iniciar', :as => :iniciar, :action => :iniciar
    end
  end

  resources :prestaciones do
    get :validar_codigo , on: :collection
    get :edit_para_asignacion_de_precios, on: :member
  end
 
  resources :solicitudes_addendas, :except => :destroy
  

  root :to => 'inicio#index'


 

end

app/views/convenios_de_gestion/_form.html.haml
= form_for(@convenio_de_gestion) do |f|

  %h3.first-header-with-note Datos de identificación
  - if @convenio_de_gestion.new_record?
    %p.note Verifique la corrección de estos datos, ya que después de guardarlos no podrán modificarse
    %div.field
      = f.label :numero, "Número*"
      = f.text_field :numero, :style => "text-transform: uppercase;"
    %div.field
      = f.label :efector, "Efector*"
      = f.select :efector_id, options_for_select(@efectores, @efector_id), { :include_blank => true }
  - else
    %p.note Estos datos no pueden modificarse
    %div.field_content
      %span.field_name Número
      %span.field_value= @convenio_de_gestion.numero
    %div.field
      %span.field_name Efector administrado
      %span.field_value= @convenio_de_gestion.efector.nombre

  %h3 Datos del firmante y fechas
  %div.field
    = f.label :firmante, "Firmante por el efector"
    = f.text_field :firmante
  %div.field
    = f.label :fecha_de_suscripcion
    = f.date_select :fecha_de_suscripcion, |
      {:start_year => 2006, :end_year => Date.today.year + 1, :include_blank => true} |
  %div.field
    = f.label :fecha_de_inicio, "Fecha de inicio*"
    = f.date_select :fecha_de_inicio, |
      {:start_year => 2006, :end_year => Date.today.year + 1, :include_blank => true} |
  %div.field
    = f.label :fecha_de_finalizacion, "Fecha de finalización*"
    = f.date_select :fecha_de_finalizacion, |
      {:start_year => 2006, :end_year => Date.today.year + 10, :include_blank => true} |

  %h3.header-with-note Direcciones de correo electrónico para notificaciones fehacientes
  %p.note Puede ingresar más de una dirección separándolas con comas (,)
  %div.field
    = f.text_field :email_notificacion

  %h3 Observaciones
  %div.field
    = f.text_area :observaciones, :size => "80x8"

  %h3 Prestaciones autorizadas por el convenio
  %div.field
    = f.select :prestacion_autorizada_ids, options_for_select(@prestaciones, @prestacion_autorizada_ids), {}, |
      { :multiple => true, :size => 15, :title => "Mantenga presionado 'Ctrl' al hacer clic para seleccionar varias opciones" } |

  %div.actions
    - if @convenio_de_gestion.new_record?
      = f.submit "Crear el convenio de gestión"
      = link_to "Cancelar", convenios_de_gestion_path
    - else
      = f.submit "Guardar las modificaciones"
      = link_to "Cancelar", @convenio_de_gestion

app/views/convenios_de_gestion/addendas.html.haml
- content_for :title do
  Adendas del convenio de gestión

#content-header
  %h1 Adendas del convenio de gestión
  #action-links
    - if can? :create, Addenda
      = link_to "Agregar una adenda", new_addenda_path(:convenio_de_gestion_id => @convenio_de_gestion.id)

= render :partial => "shared/info"

#content-body
  %h3 Convenio de gestión
  %div.field_content
    %span.field_name Número
    %span.field_value= @convenio_de_gestion.numero
    = link_to "Ver detalles del convenio", @convenio_de_gestion
  %div.field
    %span.field_name Efector
    %span.field_value= @convenio_de_gestion.efector.nombre
    = link_to "Ver detalles del efector", @convenio_de_gestion.efector

  %h3 Adendas que modifican este convenio
  - if @convenio_de_gestion.addendas.any? then
    %table
      %thead
        %tr
          %th Fecha de inicio
          %th Prestaciones dadas de alta
          %th Prestaciones dadas de baja
          %th Observaciones
      %tbody
        - @convenio_de_gestion.addendas.order(:fecha_de_inicio).each do |a|
          %tr.clickable{ |
            :onclick => "location.href=\'#{addenda_path(a)}\'", |
            :title => "Ver detalles de la adenda suscrita el #{a.fecha_de_suscripcion.strftime("%d/%m/%Y")}" } |
            %td= a.fecha_de_inicio.strftime("%d/%m/%Y")
            - if a.prestaciones_autorizadas_alta.any? then
              %td= a.prestaciones_autorizadas_alta.collect{ |pa| [pa.prestacion.codigo]}.join(", ")
            - else
              %td Ninguna
            - if a.prestaciones_autorizadas_baja.any? then
              %td= a.prestaciones_autorizadas_baja.collect{ |pa| [pa.prestacion.codigo]}.join(", ")
            - else
              %td Ninguna
            %td= a.observaciones
  - else
    %div.field_content
      %span.field_empty Este convenio no registra adendas modificatorias

app/views/convenios_de_gestion/edit.html.haml
- content_for :title do
  Modificación de datos del convenio de gestión

#content-header
  %h1 Modificación de datos del convenio de gestión

= render :partial => "shared/info", :locals => {:registro => @convenio_de_gestion}

#content-body
  %h2.first-header-with-note Formulario de modificación de datos del convenio de gestión
  %p.note Los campos marcados con asterisco (*) son obligatorios

  = render 'form'

app/views/convenios_de_gestion/index.html.haml
- content_for :title do
  Convenios de gestión

#content-header
  %h1 Convenios de gestión
  - if can? :create, ConvenioDeGestion
    #action-links
      = link_to "Agregar un convenio", new_convenio_de_gestion_url

= render :partial => "shared/info"

#content-body
  %h2.first-header Listado de convenios de gestión

  %table
    %thead
      %tr
        %th Convenio
        %th Efector
        %th Inicio
        %th Última modificación
    %tbody
      - @convenios_de_gestion.each do |c|
        %tr.clickable{ |
          :onclick => "location.href=\'#{convenio_de_gestion_path(c)}\'", :title => "Ver detalles del convenio #{c.numero}" } |
          %td= c.numero
          %td= c.efector.nombre
          %td= c.fecha_de_inicio.strftime("%d/%m/%Y")
          %td= c.updated_at.strftime("%d/%m/%Y %H:%M:%S")
  = will_paginate @convenios_de_gestion, :inner_window => 2, :outer_window => 0

app/views/convenios_de_gestion/new.html.haml
- content_for :title do
  Creación de un nuevo convenio de gestión

#content-header
  %h1 Creación de un nuevo convenio de gestión

= render :partial => "shared/info", :locals => { :registro => @convenio_de_gestion }

#content-body
  %h2.first-header-with-note Formulario de creación de un convenio de gestión
  %p.note Los campos marcados con asterisco (*) son obligatorios

  = render 'form'

app/views/convenios_de_gestion/show.html.haml
- content_for :title do
  Información detallada del convenio de gestión

#content-header
  %h1 Información detallada del convenio de gestión
  #action-links
    - if can? :update, ConvenioDeGestion
      = link_to "Modificar el convenio", edit_convenio_de_gestion_path(@convenio_de_gestion)
    - if can? :read, Addenda
      = link_to "Ver las adendas al convenio", addendas_del_convenio_de_gestion_path(@convenio_de_gestion)
    - if can? :create, Addenda
      = link_to "Agregar una adenda", new_addenda_url(:convenio_de_gestion_id => @convenio_de_gestion.id)

= render :partial => "shared/info"

#content-body
  %h3 Datos de identificación
  %div.field_content
    %span.field_name Número
    %span.field_value= @convenio_de_gestion.numero
  %div.field
    %span.field_name Efector
    %span.field_value= @convenio_de_gestion.efector.nombre
    = link_to "Ver detalles del efector", @convenio_de_gestion.efector

  %h3 Datos del firmante y fechas
  %div.field_content
    %span.field_name Firmante por el efector
    - if !@convenio_de_gestion.firmante.blank?
      %span.field_value= @convenio_de_gestion.firmante
    - else
      %span.field_empty No se ingresó el firmante
  %div.field_content
    %span.field_name Fecha de suscripción
    - if @convenio_de_gestion.fecha_de_suscripcion
      %span.field_value= @convenio_de_gestion.fecha_de_suscripcion.strftime("%d/%m/%Y")
    - else
      %span.field_empty No se indicó la fecha de suscripción
  %div.field_content
    %span.field_name Fecha de inicio
    - if @convenio_de_gestion.fecha_de_inicio
      %span.field_value= @convenio_de_gestion.fecha_de_inicio.strftime("%d/%m/%Y")
    - else
      %span.field_empty No se indicó la fecha de inicio
  %div.field_content
    %span.field_name Fecha de finalización
    - if @convenio_de_gestion.fecha_de_finalizacion
      %span.field_value= @convenio_de_gestion.fecha_de_finalizacion.strftime("%d/%m/%Y")
    - else
      %span.field_empty No se indicó la fecha de finalización

  %h3 Direcciones de correo electrónico para notificaciones fehacientes
  %div.field_content
    - if !@convenio_de_gestion.email_notificacion.blank?
      %span.field_value_multiline
        - @convenio_de_gestion.email_notificacion.split(',').each do |email|
          = mail_to(email.strip, email.strip)
          %br/
    - else
      %span.field_empty No se ingresó la dirección de correo electrónico

  %h3 Observaciones
  %div.field_content
    - if !@convenio_de_gestion.observaciones.blank?
      %span.field_value_multiline
        - @convenio_de_gestion.observaciones.split("\n").each do |linea|
          = linea
          %br/
    - else
      %span.field_empty No se han ingresado observaciones para el convenio de gestión

  %h3 Prestaciones autorizadas en el convenio original sin tener en cuenta las adendas
  - if @convenio_de_gestion.prestaciones_autorizadas.any?
    %table
      %thead
        %tr
          %th Código
          %th Nombre
      %tbody
        - @convenio_de_gestion.prestaciones_autorizadas.each do |c|
          %tr
            %td= c.prestacion.codigo
            %td= c.prestacion.nombre
  - else
    %div.field_content
      %span.field_empty Aún no se han definido prestaciones autorizadas para este convenio.