config/routes.rb
# -*- encoding : utf-8 -*-
Nacer::Application.routes.draw do

  resources :notificaciones
  put 'notificaciones/:id/edit', to: "notificaciones#update"

  scope '/(:locale)', defaults: { locale: 'es' }, constraints: { locale: /es|en/ } do
    authenticated :user, -> user { user.in_group? [:administradores,:facturacion]} do
      mount Delayed::Web::Engine => '/jobs'
    end
  end
  
  resources :procesos_de_sistemas , :only => [:index,:destroy,:show] 

  get "datos_reportables/show"
  get "prestaciones/autorizadas"
  get "diagnosticos/por_prestacion"

  # Informes de rendicion
  resources :informes_de_rendicion
  put 'informes_de_rendicion/:id/edit', to: "informes_de_rendicion#update"
  post 'informes_de_rendicion/new', to: "informes_de_rendicion#create"
  get 'informes_de_rendicion/index'

  resources :documentos_generables
  resources :notas_de_debito
  resources :prestaciones_principales

  resources :informes_debitos_prestacionales do
    resources :detalles_de_debitos_prestacionales, only: [:index, :create, :destroy]
    put :iniciar, on: :member
    put :finalizar, on: :member
    put :cerrar, on: :member
  end

  resources :expedientes_sumar do
    get 'generar_caratulas_expedientes_por_liquidacion', as: :generar_caratulas_expedientes_por_liquidacion, action: :generar_caratulas_expedientes_por_liquidacion, on: :member
  end

  get "documentos_electronicos/index"
  get "capacitaciones/index"

  get 'buscar_prestacion_liquidada/:action' => 'prestaciones_liquidadas#:action'
  get 'buscar_prestacion_liquidada/por_afiliado_concepto_y_efector' => 'prestaciones_liquidadas#por_afiliado_concepto_y_efector', as: :prestaciones_liquidadas_por_afiliado_efector_concepto

  #Liquidaciones - Sumar
  resources :conceptos_de_facturacion do
    resources :documentos_generables_por_conceptos, only: [:index, :create, :destroy]
  end
  resources :periodos
  resources :tipos_periodos
  resources :formulas
  resources :grupos_de_efectores_liquidaciones

  resources :liquidaciones_sumar do
    get '/efectores/:id', to: 'liquidaciones_sumar#detalle_de_prestaciones_liquidadas_por_efector', as: 'detalle_de_prestaciones_liquidadas_por_efector'
    member do
      post   'procesar_liquidaciones',  as: :procesar_liquidaciones, action: :procesar_liquidaciones
      post   'procesar_liquidacion', as: :procesar_liquidacion, action: :procesar_liquidacion
      post   'generar_cuasifacturas', as: :generar_cuasifacturas, action: :generar_cuasifacturas
      delete 'vaciar_liquidacion', :as => :vaciar_liquidacion, :action => :vaciar_liquidacion
    end
  end
  
  resources :solicitudes_addendas do
    member do
         post   'confirmar_solicitud', as: :confirmar_solicitud, action: :confirmar_solicitud
         post   'aprobacion_tecnica' , as: :aprobacion_tecnica, action: :aprobacion_tecnica
         post   'aprobacion_legal'   , as: :aprobacion_legal, action: :aprobacion_legal
         post   'anular_solicitud'   , as: :anular_solicitud, action: :anular_solicitud
    end
  end
  
  
  resources :reglas
  resources :liquidaciones_sumar_anexos_administrativos do
    put :finalizar_anexo, on: :member
  end
  resources :liquidaciones_sumar_anexos_medicos do
    put :finalizar_anexo, on: :member
  end
  resources :plantillas_de_reglas
  # resources :liquidaciones_sumar_cuasifacturas_detalles
  resources :liquidaciones_sumar_cuasifacturas
  resources :parametros_liquidaciones_sumar
  resources :liquidaciones_informes do
    member do
      post 'cerrar', as: :cerrar, action: :cerrar
    end
  end

  resources :secciones_pdss, only: [] do
    resources :grupos_pdss, only: :index
  end

  resources :grupos_pdss, only: [] do
    resources :grupos_poblacionales, only: :index
    resources :sexos, only: :index
  end

  resources :consolidados_sumar
  # rutas para la actualizacion asincronica
  resources :anexos_medicos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end
  resources :anexos_administrativos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end

  resources :datos_reportables , :only => :show

  devise_for :users, :controllers => { :sessions => "user_sessions", :registrations => "users", :passwords => "passwords" }
  devise_scope :user do
    get "users", :to => "users#index", :as => :users
    get "users/:id", :to => "users#admin_edit", :as => :user
    get "users/:id/edit", :to => "users#admin_edit", :as => :edit_user
    put "users/:id", :to => "users#admin_update"
    get "seleccionar_uad" => "user_sessions#seleccionar_uad", :as => :seleccionar_uad
    delete "users/:id", :to => "users#destroy", :as => :delete_user
  end
  resources :convenios_de_administracion, :except => :destroy
  resources :convenios_de_gestion, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
  end
  resources :convenios_de_administracion_sumar, :except => :destroy
  resources :convenios_de_gestion_sumar, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
    get 'firmante', :on => :member
  end
  resources :efectores, :except => :destroy do
    get 'prestaciones_autorizadas', :on => :member, :as => :prestaciones_autorizadas_del
    get 'referentes', :on => :member, :as => :referentes_del
  end
  resources :paises, :except => :destroy
  resources :provincias, :except => :destroy
  resources :departamentos, :except => :destroy
  resources :distritos, :except => :destroy
  resources :informes, :except => :destroy do
    get "informe_solicitado", on: :collection, as: :render_informe_default, action: :render_informe
  end
  resources :addendas, :except => :destroy
  resources :addendas_sumar, :except => :destroy do
    get 'new_masivo', :on => :collection, :as => :new_masivo
    post 'create_masivo', :on => :collection, :as => :create_masivo
  end
  resources :nomencladores, :except => :destroy do
    get 'asignar_precios', :on => :member, :as => :new_asignar_precios, :action => :new_asignar_precios
    get 'grupo_pdss/:grupo_pdss_id/asignar_precios', :on => :member, :as => :new_asignar_precios_por_grupo_pdss, :action => :new_asignar_precios_por_grupo_pdss
    put 'update_asignar_precios', :on => :member, :as => :update_asignar_precios, :action => :update_asignar_precios
  end
  resources :busqueda, :only => :index
  resources :verificador, :only => :index
  resources :padrones, :only => :index do
    post 'cierre', :on => :collection, :as => :cierre_de
  end
  resources :referentes, :except => [:index, :show, :destroy]
  resources :contactos#, :except => :destroy
  resources :liquidaciones, :except => :destroy
  resources :cuasi_facturas, :except => :destroy
  match "importar_detalle" => "cuasi_facturas#importar_detalle"
  match "importar_registros_de_prestaciones" => "cuasi_facturas#importar_registros_de_prestaciones"
  match "importar_archivo_p" => "liquidaciones#importar_archivo_p"
  match "procesar_bajas" => "novedades_de_los_afiliados#procesar_bajas"
  resources :novedades_de_los_afiliados, :except => [:new, :create] do
    get 'alta', :on => :collection, :as => :new_alta, :action => :new_alta
    get 'baja', :on => :collection, :as => :new_baja, :action => :new_baja
    get 'modificacion', :on => :collection, :as => :new_modificacion, :action => :new_modificacion
    post 'alta', :on => :collection, :as => :create_alta, :action => :create_alta
    post 'baja', :on => :collection, :as => :create_baja, :action => :create_baja
    post 'modificacion', :on => :collection, :as => :create_modificacion, :action => :create_modificacion
  end
  resources :afiliados, :only => [:show] do
    get :busqueda_por_aproximacion, on: :collection
    get 'prestaciones_brindadas', :on => :member, :as => :prestaciones_brindadas_al
  end
  resources :unidades_de_alta_de_datos, :except => :destroy
  resources :prestaciones_brindadas
  match "informe_de_beneficiarios_activos" => "informes#beneficiarios_activos"
  match "tablero_de_comandos_alto_impacto" => "informes#tablero_de_comandos_alto_impacto"
  resources :procesos_de_datos_externos, :except => :destroy do
    member do
      post 'aplicar', :as => :aplicar, :action => :aplicar
      post 'iniciar', :as => :iniciar, :action => :iniciar
    end
  end

  resources :prestaciones do
    get :validar_codigo , on: :collection
    get :edit_para_asignacion_de_precios, on: :member
  end
 
  resources :solicitudes_addendas, :except => :destroy
  

  root :to => 'inicio#index'


 

end

app/views/procesos_de_datos_externos/_form.html.haml
= form_for(@proceso) do |f|
  %h3.first-header Datos del proceso

  %div.field
    = f.label :tipo_de_proceso_id, "Tipo de proceso*"
    = f.select :tipo_de_proceso_id, @tipos_de_procesos, {:include_blank => true}, {:class => 'select2'}

  %div.field
    = f.label :archivo_de_datos, "Archivo a procesar*"
    = f.file_field :archivo_de_datos, {:accept => "text/plain, text/csv"}

  %div.field
    = f.label :notificar_por_email, "Notificar por email al concluir el proceso"
    = f.check_box :notificar_por_email

  %h3 Observaciones
  %div.field
    = f.text_area :observaciones, :size => "80x8"

  %div.actions
    - if @proceso.new_record?
      = f.submit "Crear el proceso"
      = link_to "Cancelar", procesos_de_datos_externos_url
    - else
      = f.submit "Guardar las modificaciones"
      = link_to "Cancelar", @proceso

app/views/procesos_de_datos_externos/edit.html.haml
- content_for :title do
  Modificación del proceso de datos externos

#content-header
  %h1 Modificación del proceso de datos externos

= render :partial => "shared/info", :locals => { :registro => @proceso }

#content-body
  %h2.first-header-with-note Formulario de modificación del proceso de datos externos
  %p.note Los campos marcados con asterisco (*) son obligatorios

  = render "form"

app/views/procesos_de_datos_externos/index.html.haml
- content_for :title do
  Procesos de datos externos

#content-header
  %h1 Procesos de datos externos
  - if can? :create, ProcesoDeDatosExternos
    #action-links
      = link_to "Crear un nuevo proceso", new_proceso_de_datos_externos_url

= render :partial => "shared/info"

#content-body
  %h2.first-header Listado de procesos de datos externos

  - if @procesos.size > 0
    %table
      %thead
        %tr
          %th Tipo de proceso
          %th Archivo de datos
          %th Estado del proceso
      %tbody
        - @procesos.each do |p|
          %tr.clickable{ :onclick => "location.href=\'#{proceso_de_datos_externos_path(p)}\'", :title => "Ver detalles del proceso" }
            %td= p.tipo_de_proceso.nombre
            %td= p.archivo_de_datos_file_name
            %td
              - if p.proceso_aplicado
                Proceso finalizado y aplicado
              - elsif p.proceso_finalizado.present?
                El proceso se finalizó, pero aún no fue aplicado
              - elsif p.ultimo_fallo.present?
                Se produjo un error al procesar el archivo, comuníquese con el área de sistemas
              - elsif p.proceso_iniciado.present?
                El proceso se encuentra en ejecución. Porcentaje de avance:
                = p.porcentaje_de_avance
              - elsif p.proceso_solicitado.present?
                El proceso se encuentra en la cola de espera
              - else
                Se ha creado el proceso, pero aún no se ha solicitado el procesamiento
    = will_paginate @procesos, :inner_window => 2, :outer_window => 0
  - else
    No se ha creado ningún proceso de datos externos

app/views/procesos_de_datos_externos/new.html.haml
- content_for :title do
  Creación de un nuevo proceso de datos externos

#content-header
  %h1 Creación de un nuevo proceso de datos externos

= render :partial => "shared/info", :locals => { :registro => @proceso }

#content-body
  %h2.first-header-with-note Formulario de creación de un nuevo proceso
  %p.note Los campos marcados con asterisco (*) son obligatorios

  = render 'form'

app/views/procesos_de_datos_externos/show.html.haml
- content_for :title do
  Información detallada del proceso de datos externos

#content-header
  %h1 Información detallada del proceso de datos externos
  #action-links
    - if can?(:update, ProcesoDeDatosExternos) && @proceso.modificable?
      = link_to "Modificar el proceso", edit_proceso_de_datos_externos_path(@proceso)
    - if !@proceso.proceso_solicitado.present?  && @proceso.cantidad_de_lineas_validas > 0
      = link_to "Iniciar procesamiento", iniciar_proceso_de_datos_externos_path(@proceso), :method => :post
    - if @proceso.proceso_finalizado.present? && !@proceso.proceso_aplicado
      = link_to "Aplicar proceso", aplicar_proceso_de_datos_externos_path(@proceso), :method => :post

= render :partial => "shared/info"

#content-body
  %h3 Datos del proceso

  %div.field_content
    %span.field_name Tipo de proceso seleccionado
    - if @proceso.tipo_de_proceso.present?
      %span.field_value= @proceso.tipo_de_proceso.nombre
    - else
      %span.field_empty No se ha definido el tipo de proceso
  %div.field_content
    %span.field_name Estado del proceso
    - if @proceso.proceso_aplicado
      %span.field_value Proceso finalizado y aplicado
    - elsif @proceso.proceso_finalizado.present?
      %span.field_value El proceso se finalizó, pero aún no fue aplicado
    - elsif @proceso.ultimo_fallo.present?
      %span.field_value Se produjo un error al procesar el archivo, comuníquese con el área de sistemas
    - elsif @proceso.proceso_iniciado.present?
      %span.field_value
        El proceso se encuentra en ejecución. Porcentaje de avance:
        = p.porcentaje_de_avance
    - elsif @proceso.proceso_solicitado.present?
      %span.field_value El proceso se encuentra en la cola de espera
    - else
      %span.field_value Se ha creado el proceso, pero aún no se ha solicitado el procesamiento

  %h3 Información del archivo cargado
  %div.field_content
    %span.field_name Nombre del archivo cargado
    - if !@proceso.archivo_de_datos_file_name.blank?
      %span.field_value= @proceso.archivo_de_datos_file_name
    - else
      %span.field_empty No se ha cargado ningún archivo
  %div.field_content
    %span.field_name Tamaño del archivo
    - if @proceso.archivo_de_datos_file_size.present?
      %span.field_value
        - if @proceso.archivo_de_datos_file_size > 1000000
          = ("%.1f" % (@proceso.archivo_de_datos_file_size.to_f / 1000000.to_f)) + " Mb"
        - elsif @proceso.archivo_de_datos_file_size > 1000
          = ("%.1f" % (@proceso.archivo_de_datos_file_size.to_f / 1000.to_f)) + " Kb"
        - else
          = "#{@proceso.archivo_de_datos_file_size} b"
    - else
      %span.field_empty No se ha cargado ningún archivo
  %div.field_content
    %span.field_name Cantidad de líneas totales
    - if !@proceso.tabla_de_preprocesamiento.blank?
      %span.field_value= @proceso.cantidad_de_lineas_totales
    - else
      %span.field_empty No se ha cargado ningún archivo
  %div.field_content
    %span.field_name Cantidad de líneas con sintaxis válida para el procesamiento
    - if !@proceso.tabla_de_preprocesamiento.blank?
      %span.field_value= @proceso.cantidad_de_lineas_validas
      - if @proceso.cantidad_de_lineas_validas == 0 && !@proceso.proceso_solicitado.present?
        %span.note (El proceso no podrá iniciarse porque no existe ninguna línea con sintaxis correcta)
    - else
      %span.field_empty No se ha cargado ningún archivo

  %h3 Observaciones
  %div.field_content
    - if !@proceso.observaciones.blank?
      %span.field_value_multiline
        - @proceso.observaciones.split("\n").each do |linea|
          = linea
          %br/
    - else
      %span.field_empty No se han ingresado observaciones para el proceso