config/routes.rb
# -*- encoding : utf-8 -*-
Nacer::Application.routes.draw do

  resources :notificaciones
  put 'notificaciones/:id/edit', to: "notificaciones#update"

  scope '/(:locale)', defaults: { locale: 'es' }, constraints: { locale: /es|en/ } do
    authenticated :user, -> user { user.in_group? [:administradores,:facturacion]} do
      mount Delayed::Web::Engine => '/jobs'
    end
  end
  
  resources :procesos_de_sistemas , :only => [:index,:destroy,:show] 

  get "datos_reportables/show"
  get "prestaciones/autorizadas"
  get "diagnosticos/por_prestacion"

  # Informes de rendicion
  resources :informes_de_rendicion
  put 'informes_de_rendicion/:id/edit', to: "informes_de_rendicion#update"
  post 'informes_de_rendicion/new', to: "informes_de_rendicion#create"
  get 'informes_de_rendicion/index'

  resources :documentos_generables
  resources :notas_de_debito
  resources :prestaciones_principales

  resources :informes_debitos_prestacionales do
    resources :detalles_de_debitos_prestacionales, only: [:index, :create, :destroy]
    put :iniciar, on: :member
    put :finalizar, on: :member
    put :cerrar, on: :member
  end

  resources :expedientes_sumar do
    get 'generar_caratulas_expedientes_por_liquidacion', as: :generar_caratulas_expedientes_por_liquidacion, action: :generar_caratulas_expedientes_por_liquidacion, on: :member
  end

  get "documentos_electronicos/index"
  get "capacitaciones/index"

  get 'buscar_prestacion_liquidada/:action' => 'prestaciones_liquidadas#:action'
  get 'buscar_prestacion_liquidada/por_afiliado_concepto_y_efector' => 'prestaciones_liquidadas#por_afiliado_concepto_y_efector', as: :prestaciones_liquidadas_por_afiliado_efector_concepto

  #Liquidaciones - Sumar
  resources :conceptos_de_facturacion do
    resources :documentos_generables_por_conceptos, only: [:index, :create, :destroy]
  end
  resources :periodos
  resources :tipos_periodos
  resources :formulas
  resources :grupos_de_efectores_liquidaciones

  resources :liquidaciones_sumar do
    get '/efectores/:id', to: 'liquidaciones_sumar#detalle_de_prestaciones_liquidadas_por_efector', as: 'detalle_de_prestaciones_liquidadas_por_efector'
    member do
      post   'procesar_liquidaciones',  as: :procesar_liquidaciones, action: :procesar_liquidaciones
      post   'procesar_liquidacion', as: :procesar_liquidacion, action: :procesar_liquidacion
      post   'generar_cuasifacturas', as: :generar_cuasifacturas, action: :generar_cuasifacturas
      delete 'vaciar_liquidacion', :as => :vaciar_liquidacion, :action => :vaciar_liquidacion
    end
  end
  
  resources :solicitudes_addendas do
    member do
         post   'confirmar_solicitud', as: :confirmar_solicitud, action: :confirmar_solicitud
         post   'aprobacion_tecnica' , as: :aprobacion_tecnica, action: :aprobacion_tecnica
         post   'aprobacion_legal'   , as: :aprobacion_legal, action: :aprobacion_legal
         post   'anular_solicitud'   , as: :anular_solicitud, action: :anular_solicitud
    end
  end
  
  
  resources :reglas
  resources :liquidaciones_sumar_anexos_administrativos do
    put :finalizar_anexo, on: :member
  end
  resources :liquidaciones_sumar_anexos_medicos do
    put :finalizar_anexo, on: :member
  end
  resources :plantillas_de_reglas
  # resources :liquidaciones_sumar_cuasifacturas_detalles
  resources :liquidaciones_sumar_cuasifacturas
  resources :parametros_liquidaciones_sumar
  resources :liquidaciones_informes do
    member do
      post 'cerrar', as: :cerrar, action: :cerrar
    end
  end

  resources :secciones_pdss, only: [] do
    resources :grupos_pdss, only: :index
  end

  resources :grupos_pdss, only: [] do
    resources :grupos_poblacionales, only: :index
    resources :sexos, only: :index
  end

  resources :consolidados_sumar
  # rutas para la actualizacion asincronica
  resources :anexos_medicos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end
  resources :anexos_administrativos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end

  resources :datos_reportables , :only => :show

  devise_for :users, :controllers => { :sessions => "user_sessions", :registrations => "users", :passwords => "passwords" }
  devise_scope :user do
    get "users", :to => "users#index", :as => :users
    get "users/:id", :to => "users#admin_edit", :as => :user
    get "users/:id/edit", :to => "users#admin_edit", :as => :edit_user
    put "users/:id", :to => "users#admin_update"
    get "seleccionar_uad" => "user_sessions#seleccionar_uad", :as => :seleccionar_uad
    delete "users/:id", :to => "users#destroy", :as => :delete_user
  end
  resources :convenios_de_administracion, :except => :destroy
  resources :convenios_de_gestion, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
  end
  resources :convenios_de_administracion_sumar, :except => :destroy
  resources :convenios_de_gestion_sumar, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
    get 'firmante', :on => :member
  end
  resources :efectores, :except => :destroy do
    get 'prestaciones_autorizadas', :on => :member, :as => :prestaciones_autorizadas_del
    get 'referentes', :on => :member, :as => :referentes_del
  end
  resources :paises, :except => :destroy
  resources :provincias, :except => :destroy
  resources :departamentos, :except => :destroy
  resources :distritos, :except => :destroy
  resources :informes, :except => :destroy do
    get "informe_solicitado", on: :collection, as: :render_informe_default, action: :render_informe
  end
  resources :addendas, :except => :destroy
  resources :addendas_sumar, :except => :destroy do
    get 'new_masivo', :on => :collection, :as => :new_masivo
    post 'create_masivo', :on => :collection, :as => :create_masivo
  end
  resources :nomencladores, :except => :destroy do
    get 'asignar_precios', :on => :member, :as => :new_asignar_precios, :action => :new_asignar_precios
    get 'grupo_pdss/:grupo_pdss_id/asignar_precios', :on => :member, :as => :new_asignar_precios_por_grupo_pdss, :action => :new_asignar_precios_por_grupo_pdss
    put 'update_asignar_precios', :on => :member, :as => :update_asignar_precios, :action => :update_asignar_precios
  end
  resources :busqueda, :only => :index
  resources :verificador, :only => :index
  resources :padrones, :only => :index do
    post 'cierre', :on => :collection, :as => :cierre_de
  end
  resources :referentes, :except => [:index, :show, :destroy]
  resources :contactos#, :except => :destroy
  resources :liquidaciones, :except => :destroy
  resources :cuasi_facturas, :except => :destroy
  match "importar_detalle" => "cuasi_facturas#importar_detalle"
  match "importar_registros_de_prestaciones" => "cuasi_facturas#importar_registros_de_prestaciones"
  match "importar_archivo_p" => "liquidaciones#importar_archivo_p"
  match "procesar_bajas" => "novedades_de_los_afiliados#procesar_bajas"
  resources :novedades_de_los_afiliados, :except => [:new, :create] do
    get 'alta', :on => :collection, :as => :new_alta, :action => :new_alta
    get 'baja', :on => :collection, :as => :new_baja, :action => :new_baja
    get 'modificacion', :on => :collection, :as => :new_modificacion, :action => :new_modificacion
    post 'alta', :on => :collection, :as => :create_alta, :action => :create_alta
    post 'baja', :on => :collection, :as => :create_baja, :action => :create_baja
    post 'modificacion', :on => :collection, :as => :create_modificacion, :action => :create_modificacion
  end
  resources :afiliados, :only => [:show] do
    get :busqueda_por_aproximacion, on: :collection
    get 'prestaciones_brindadas', :on => :member, :as => :prestaciones_brindadas_al
  end
  resources :unidades_de_alta_de_datos, :except => :destroy
  resources :prestaciones_brindadas
  match "informe_de_beneficiarios_activos" => "informes#beneficiarios_activos"
  match "tablero_de_comandos_alto_impacto" => "informes#tablero_de_comandos_alto_impacto"
  resources :procesos_de_datos_externos, :except => :destroy do
    member do
      post 'aplicar', :as => :aplicar, :action => :aplicar
      post 'iniciar', :as => :iniciar, :action => :iniciar
    end
  end

  resources :prestaciones do
    get :validar_codigo , on: :collection
    get :edit_para_asignacion_de_precios, on: :member
  end
 
  resources :solicitudes_addendas, :except => :destroy
  

  root :to => 'inicio#index'


 

end

app/controllers/rendiciones_controller.rb
# -*- encoding : utf-8 -*-
class RendicionesController < ApplicationController
  before_filter :cargar_selects, :only => [:show, :new, :edit]

  # GET /rendiciones
  # GET /rendiciones.json
  def index
    @rendiciones = Rendicion.all
  end

  # GET /rendiciones/1 
  # GET /rendiciones/1.json
  def show
    @rendicion = Rendicion.find(params[:id])
    @rendiciones_detalles = @rendicion.rendiciones_detalles.where(id: params[:id])
  end

  # GET /rendiciones/new
  # GET /rendiciones/new.json
  def new
    @rendicion = Rendicion.new
    @rendicion.rendiciones_detalles.build
  end

  # GET /rendiciones/1/edit
  def edit
    @rendicion = Rendicion.find(params[:id])
    if @rendicion.estado_de_rendicion_id == 3
      redirect_to @rendicion, notice: 'La rendicon de encuentra cerrada y no puede ser modificada.' 
    end
  end

  # POST /rendiciones
  # POST /rendiciones.json
  def create
    @rendicion = Rendicion.new(params[:rendicion])
    #validacion de la existencia del registro del efector para el pediodo
 
    if @rendicion.save
      redirect_to @rendicion, notice: 'La rendicion y su detalle fueron guardados con exito.' 
    else
      @efectores = Efector.all.map { |ef| [ef.nombre, ef.id]}          
      @periodos_de_rendicion = PeriodoDeRendicion.all.map {|pr| [pr.nombre, pr.id]}
      @tipos_de_gasto = TipoDeGasto.all.map {|tg| [tg.nombre, tg.id]}
      render action: "new" 
    end
  end

  # PUT /rendiciones/1
  # PUT /rendiciones/1.json
  def update
    @rendicion = Rendicion.find(params[:id])

    respond_to do |format|
      if @rendicion.update_attributes(params[:rendicion])
        format.html { redirect_to @rendicion, notice: 'Rendicion was successfully updated.' }
        format.json { head :no_content }
      else
        @efectores = Efector.all.map { |ef| [ef.nombre, ef.id]}          
        @periodos_de_rendicion = PeriodoDeRendicion.all.map {|pr| [pr.nombre, pr.id]}
        @tipos_de_gasto = TipoDeGasto.all.map {|tg| [tg.nombre, tg.id]}
        format.html { render action: "edit" }
        format.json { render json: @rendicion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rendiciones/1
  # DELETE /rendiciones/1.json
  def destroy
    @rendicion = Rendicion.find(params[:id])
    @rendicion.destroy

    respond_to do |format|
      format.html { redirect_to rendiciones_url }
      format.json { head :no_content }
    end
  end

  def actualizar_estado
    # @estado_de_rendicion = EstadoDeRendicion.all.map do |er|
    #   [er.nombre, er.id]
    # end
    #      @efectores = Efector.all.map do |ef|
    #   [ef.nombre, ef.id]
    # end   
    # @periodos_de_rendicion = PeriodoDeRendicion.all.map do |pr|
    #   [pr.nombre, pr.id]
    # end

    @estado_de_rendicion = EstadoDeRendicion.all.map do |er|
      [er.nombre, er.id]
    end
    # @tipos_de_gasto = TipoDeGasto.all.map do |tg|
    #   [tg.nombre, tg.id]
    # end
    @rendicion = Rendicion.find(params[:id])
    @rendiciones_detalles = @rendicion.rendiciones_detalles.where(id: params[:id])
    #@rendicion.estado_de_rendicion_id = 1
    @rendicion.save!
  end

  def imprimir
    @rendicion = Rendicion.find(params[:id])
    @rendicion_detalle = @rendicion.rendiciones_detalles.where(id: params[:id])
    # Armar el reporte
    reporte = ODFReport::Report.new("lib/assets/informe_rendicion2.odt") do |r|
      r.add_field :efector,             @rendicion.efector.nombre
      r.add_field :departamento,        @rendicion.efector.departamento.nombre
      r.add_field :banco,               @rendicion.efector.banco_cuenta_principal
      r.add_field :ctacte,              @rendicion.efector.numero_de_cuenta_principal
      r.add_field :cuit,                @rendicion.efector.cuit
      r.add_field :periodo,             @rendicion.periodo_de_rendicion.nombre
      r.add_table("FIELDS", @rendicion.rendiciones_detalles, :header=>true) do |t|
        t.add_column(:fecha) { |rendicion_detalle|  "#{rendicion_detalle.fecha}" }
        t.add_column(:detalle) { |rendicion_detalle| "#{rendicion_detalle.detalle}" }
        t.add_column(:cantidad) { |rendicion_detalle| "#{rendicion_detalle.cant}" }
        t.add_column(:numero) { |rendicion_detalle| "#{rendicion_detalle.nro_factura}" }
        t.add_column(:cheque) { |rendicion_detalle| "#{rendicion_detalle.nro_cheque}" }
        t.add_column(:importe) { |rendicion_detalle| "$#{rendicion_detalle.importe_gasto}" }
        t.add_column(:bien) { |rendicion_detalle| "#{rendicion_detalle.tipo_de_gasto.nombre}" }
        #  @total += rendicion_detalle.importe_gasto
      end
      r.add_field :total,      "$#{@rendicion.rendiciones_detalles.sum('importe_gasto')}"
    end
    nombre_archivo = Cocaine::CommandLine.new("mktemp", "--tmpdir=tmp/ -u report_XXXXXXXXXX").run.chomp
    reporte.generate(nombre_archivo + ".odt")

    Cocaine::CommandLine.new("unoconv", "-f pdf -e EnableCopyingOfContent -e ExportFormFields -e FormsType=FDF #{nombre_archivo}.odt").run
    send_file "#{nombre_archivo}.pdf", type: 'application/pdf', disposition: 'attachment'
   
  end


  def cargar_selects
    @efectores = Efector.all.map do |ef|
      [ef.nombre, ef.id]
    end   
    @periodos_de_rendicion = PeriodoDeRendicion.all.map do |pr|
      [pr.nombre, pr.id]
    end
    @estado_de_rendicion = EstadoDeRendicion.all.map do |er|
      [er.nombre, er.id]
    end
    @tipos_de_gasto = TipoDeGasto.all.map do |tg|
      [tg.nombre, tg.id]
    end
  end

end

app/helpers/rendiciones_helper.rb
module RendicionesHelper
end

app/views/rendiciones/_form.html.haml
= form_for(@rendicion) do |f|
  .field
    = f.label :efector
    %br/
    = f.select(:efector_id, @efectores,{include_blank: true}, class: "select2")
  .field
    = f.label :periodo_de_rendicion_id
    %br/
    = f.select(:periodo_de_rendicion_id, @periodos_de_rendicion,{include_blank: true}, class: "select2")
  .field
    = f.label :observaciones
    %br/
    %br/
    = f.text_area :observaciones, {rows: "3"}
    #rendiciones_detalles
      %br/
      %br/
      %table{:border => "0", :width => "90%", :id => 'div_det_ren'}
        %thead
        %tbody#rendiciones_detalles
          = f.fields_for :rendiciones_detalles do |detalle|
            = render 'rendicion_detalle_fields', f: detalle
      #action-links
        = link_to_add_association 'Agregar Fila de detalle', f, :rendiciones_detalles, force_non_association_create: true, data: {'association-insertion-node' => 'tbody#rendiciones_detalles', 'association-insertion-method' => 'append', "cocoon:after-insert" => "true"}
  .actions
    = f.submit

app/views/rendiciones/_form2.html.haml
#content-header
  %h1 Listado de detalle de rendion del efector:
  - #if @rendicion.estado_de_rendicion.id == 3
  - # #errorExplanation
  - #  %h2
  - #    = pluralize(@post.errors.count, "error")
  - #   prohibited this post from being saved:
  - # %ul
  - #   - @post.errors.full_messages.each do |msg|
  - #   %li= msg

#action-links
  = link_to 'Volver', rendiciones_path
#content-body
  %div.field_content 
    %span.field_name Efector:
    %span.field_value= @rendicion.efector.nombre
  %div.field_content 
    %span.field_name Periodo de rendicion:
    %span.field_value= @rendicion.periodo_de_rendicion.nombre
  -#%div.field_content 
  -#  %span.field_name Estado de actual:
  -#  %span.field_value= @rendicion.estado_de_rendicion.nombre
  %div.field_content 
    %span.field_name Nuevo estado de Rendición:
    = form_for(@rendicion) do |f|
      = f.select(:estado_de_rendicion_id, @estado_de_rendicion,{include_blank: true}, class: "select2")
      %div.field_content 
        %span.field_name Observaciones:
        %span.field_value= @rendicion.observaciones
      %hr{width:"100%"}
        %table
          %tr
            %th Fecha
            %th Nro factura
            %th Detalle
            %th Cant
            %th Nro cheque
            %th Tipo gasto
            %th Importe gasto
          - @rendicion.rendiciones_detalles.each do |rendicion_detalle|
            %tr
              %td= rendicion_detalle.fecha.strftime("%d-%m-%Y")
              %td= rendicion_detalle.nro_factura
              %td= rendicion_detalle.detalle
              %td= rendicion_detalle.cant
              %td= rendicion_detalle.nro_cheque
              %td= rendicion_detalle.tipo_de_gasto.nombre
              %td= rendicion_detalle.importe_gasto
        %hr{width:"100%"}
      = f.submit "Guardar las modificaciones"

app/views/rendiciones/_rendicion_detalle_fields.html.haml
%tr.nested-fields
  %th{:colspan => "3", class: 'th_blank'}
%tr.nested-fields
  %th{:colspan => "3"} Detalle de registro
%tr.nested-fields
  %th Fecha
  %td= f.text_field :fecha,  {width: "10px", size: "5", class: "jquery_fecha",  style: "font-size: 5"}
%tr.nested-fields
  %th{:scope => "col"} Nro Factura
  %td= f.text_field :nro_factura, :size => 5
%tr.nested-fields
  %th{:scope => "col"} Detalle
  %td= f.text_area :detalle, {rows: "2", cols: "50"}
%tr.nested-fields
  %th{:scope => "col"} Cant.
  %td= f.number_field :cant, :size => 2
%tr.nested-fields
  %th{:scope => "col"} Nro Cheque
  %td= f.number_field :nro_cheque, :width => "5px"
%tr.nested-fields
  %th{:scope => "col"} Tipo de Gasto
  %td= f.select(:tipo_de_gasto_id, @tipos_de_gasto,{include_blank: true}, class: "select2")
%tr.nested-fields
  %th{:scope => "col"} Importe de Gasto
  %td= f.number_field :importe_gasto, :size => 6
%tr.nested-fields
  %th{:scope => "col"} 
  %td= link_to_remove_association "Quitar fila", f




-#%tr.nested-fields
  -#%td= f.text_field :fecha,  {width: "10px", size: "5", class: "jquery_fecha",  style: "font-size: 5"}
  -#%td= f.text_field :nro_factura, :size => 5
  -#%td= f.text_area :detalle, {rows: "3"}
  -#%td= f.number_field :cant, :size => 2
  -#%td= f.number_field :nro_cheque, :width => "5px"
  -#%td= f.select(:tipo_de_gasto_id, @tipos_de_gasto,{include_blank: true}, class: "select2")
  -#%td= f.number_field :importe_gasto, :size => 6
  -#%td= link_to_remove_association "Quitar fila", f
 
-#:javascript
-#  $('.jquery_fecha').datepicker({  dateFormat: "yy-mm-dd", showOn: "button", buttonImage: "/assets/calendar.gif", buttonImageOnly: true });

app/views/rendiciones/actualizar_estado.html.erb
<h1>Editing rendicion</h1>

<%= render 'form2' %>

<%= link_to 'Show', @rendicion %> |
<%= link_to 'Back', rendiciones_path %>

app/views/rendiciones/actualizar_estado.html.haml
%h1 Editing rendicion
= render 'form2'
= link_to 'Show', @rendicion
|
\#{link_to 'Back', rendiciones_path}

app/views/rendiciones/edit.html.erb
<h1>Editing rendicion</h1>

<%= render 'form' %>

<%= link_to 'Show', @rendicion %> |
<%= link_to 'Back', rendiciones_path %>
 

app/views/rendiciones/edit.html.haml
= javascript_include_tag 'rendiciones'

#content-header
  %h1 Edicion de Rendiciones
  #action-links
    = link_to 'Mostrar', @rendicion
    = link_to 'Volver', rendiciones_path
#content-body
  = render 'form'
    

app/views/rendiciones/imprimir.html.erb
<h1>Imprimiendo rendicion</h1>

<%= link_to 'Back', rendiciones_path %>
 

app/views/rendiciones/index.html.haml
#content-header
  %h1 RENDICIONES
  #action-links
    = link_to 'Nueva Rendicion', new_rendicion_path
#content-body
  %h2.first-header Listado de Rendiciones
  %table
    %thead
      %tr
        %th Nº
        %th Efector
        %th Periodo rendicion
        %th Estado rendicion
        %th Observaciones
        %th{colspan:3} Acciones
    %tbody
      - @rendiciones.each do |rendicion|
        %tr.clickable{ :onclick => "location.href=\'#{rendicion_path(rendicion)}\'", :title => "Editar" }
          %td= rendicion.id
          %td= rendicion.efector.nombre
          %td= rendicion.periodo_de_rendicion.nombre
          %td= rendicion.estado_de_rendicion.nombre
          %td= rendicion.observaciones
          %td
            #action-links
              = link_to 'Detalle', rendicion
          %td
            #action-links
              = link_to 'Editar', edit_rendicion_path(rendicion)
          %td
            #action-links
              = link_to 'Cambiar Estado', actualizar_estado_rendicion_path(rendicion)        
          %td
            #action-links
              = link_to 'Imprimir', imprimir_rendicion_path(rendicion)       

app/views/rendiciones/new.html.haml
#content-header
  %h1 Crear nueva rendición

= render :partial => "shared/info", :locals => { :registro => @rendicion }

#content-body
  %h2.first-header-with-note Formulario de creación de rendiciones
  %p.note Los campos marcados con asterisco (*) son obligatorios
  = render 'form'

app/views/rendiciones/show.html.haml
#content-header
  %h1 Listado de detalle de rendion del efector:
  #action-links
    = link_to 'Volver', rendiciones_path
#content-body
  %div.field_content 
    %span.field_name Efector:
    %span.field_value= @rendicion.efector.nombre
  %div.field_content 
    %span.field_name Periodo de rendicion:
    %span.field_value= @rendicion.periodo_de_rendicion.nombre
  %div.field_content 
    %span.field_name Estado de rendicion:
    %span.field_value= @rendicion.estado_de_rendicion.nombre
  %div.field_content 
    %span.field_name Observaciones:
    %span.field_value= @rendicion.observaciones
  %hr{width:"100%"}
    %table
      %tr
        %th Fecha
        %th Nro factura
        %th Detalle
        %th Cant
        %th Nro cheque
        %th Tipo gasto
        %th Importe gasto
      - @rendicion.rendiciones_detalles.each do |rendicion_detalle|
        %tr
          %td= rendicion_detalle.fecha.strftime("%d-%m-%Y")
          %td= rendicion_detalle.nro_factura
          %td= rendicion_detalle.detalle
          %td= rendicion_detalle.cant
          %td= rendicion_detalle.nro_cheque
          %td= rendicion_detalle.tipo_de_gasto.nombre
          %td= rendicion_detalle.importe_gasto
    %hr{width:"100%"}