config/routes.rb
# -*- encoding : utf-8 -*-
Nacer::Application.routes.draw do

  resources :notificaciones
  put 'notificaciones/:id/edit', to: "notificaciones#update"

  scope '/(:locale)', defaults: { locale: 'es' }, constraints: { locale: /es|en/ } do
    authenticated :user, -> user { user.in_group? [:administradores,:facturacion]} do
      mount Delayed::Web::Engine => '/jobs'
    end
  end
  
  resources :procesos_de_sistemas , :only => [:index,:destroy,:show] 

  get "datos_reportables/show"
  get "prestaciones/autorizadas"
  get "diagnosticos/por_prestacion"

  # Informes de rendicion
  resources :informes_de_rendicion
  put 'informes_de_rendicion/:id/edit', to: "informes_de_rendicion#update"
  post 'informes_de_rendicion/new', to: "informes_de_rendicion#create"
  get 'informes_de_rendicion/index'

  resources :documentos_generables
  resources :notas_de_debito
  resources :prestaciones_principales

  resources :informes_debitos_prestacionales do
    resources :detalles_de_debitos_prestacionales, only: [:index, :create, :destroy]
    put :iniciar, on: :member
    put :finalizar, on: :member
    put :cerrar, on: :member
  end

  resources :expedientes_sumar do
    get 'generar_caratulas_expedientes_por_liquidacion', as: :generar_caratulas_expedientes_por_liquidacion, action: :generar_caratulas_expedientes_por_liquidacion, on: :member
  end

  get "documentos_electronicos/index"
  get "capacitaciones/index"

  get 'buscar_prestacion_liquidada/:action' => 'prestaciones_liquidadas#:action'
  get 'buscar_prestacion_liquidada/por_afiliado_concepto_y_efector' => 'prestaciones_liquidadas#por_afiliado_concepto_y_efector', as: :prestaciones_liquidadas_por_afiliado_efector_concepto

  #Liquidaciones - Sumar
  resources :conceptos_de_facturacion do
    resources :documentos_generables_por_conceptos, only: [:index, :create, :destroy]
  end
  resources :periodos
  resources :tipos_periodos
  resources :formulas
  resources :grupos_de_efectores_liquidaciones

  resources :liquidaciones_sumar do
    get '/efectores/:id', to: 'liquidaciones_sumar#detalle_de_prestaciones_liquidadas_por_efector', as: 'detalle_de_prestaciones_liquidadas_por_efector'
    member do
      post   'procesar_liquidaciones',  as: :procesar_liquidaciones, action: :procesar_liquidaciones
      post   'procesar_liquidacion', as: :procesar_liquidacion, action: :procesar_liquidacion
      post   'generar_cuasifacturas', as: :generar_cuasifacturas, action: :generar_cuasifacturas
      delete 'vaciar_liquidacion', :as => :vaciar_liquidacion, :action => :vaciar_liquidacion
    end
  end
  
  resources :solicitudes_addendas do
    member do
         post   'confirmar_solicitud', as: :confirmar_solicitud, action: :confirmar_solicitud
         post   'aprobacion_tecnica' , as: :aprobacion_tecnica, action: :aprobacion_tecnica
         post   'aprobacion_legal'   , as: :aprobacion_legal, action: :aprobacion_legal
         post   'anular_solicitud'   , as: :anular_solicitud, action: :anular_solicitud
    end
  end
  
  
  resources :reglas
  resources :liquidaciones_sumar_anexos_administrativos do
    put :finalizar_anexo, on: :member
  end
  resources :liquidaciones_sumar_anexos_medicos do
    put :finalizar_anexo, on: :member
  end
  resources :plantillas_de_reglas
  # resources :liquidaciones_sumar_cuasifacturas_detalles
  resources :liquidaciones_sumar_cuasifacturas
  resources :parametros_liquidaciones_sumar
  resources :liquidaciones_informes do
    member do
      post 'cerrar', as: :cerrar, action: :cerrar
    end
  end

  resources :secciones_pdss, only: [] do
    resources :grupos_pdss, only: :index
  end

  resources :grupos_pdss, only: [] do
    resources :grupos_poblacionales, only: :index
    resources :sexos, only: :index
  end

  resources :consolidados_sumar
  # rutas para la actualizacion asincronica
  resources :anexos_medicos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end
  resources :anexos_administrativos_prestaciones, :only => [] do
    put :update_status, on: :member
    put :update_motivo_rechazo, on: :member
  end

  resources :datos_reportables , :only => :show

  devise_for :users, :controllers => { :sessions => "user_sessions", :registrations => "users", :passwords => "passwords" }
  devise_scope :user do
    get "users", :to => "users#index", :as => :users
    get "users/:id", :to => "users#admin_edit", :as => :user
    get "users/:id/edit", :to => "users#admin_edit", :as => :edit_user
    put "users/:id", :to => "users#admin_update"
    get "seleccionar_uad" => "user_sessions#seleccionar_uad", :as => :seleccionar_uad
    delete "users/:id", :to => "users#destroy", :as => :delete_user
  end
  resources :convenios_de_administracion, :except => :destroy
  resources :convenios_de_gestion, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
  end
  resources :convenios_de_administracion_sumar, :except => :destroy
  resources :convenios_de_gestion_sumar, :except => :destroy do
    get 'addendas', :on => :member, :as => :addendas_del
    get 'firmante', :on => :member
  end
  resources :efectores, :except => :destroy do
    get 'prestaciones_autorizadas', :on => :member, :as => :prestaciones_autorizadas_del
    get 'referentes', :on => :member, :as => :referentes_del
  end
  resources :paises, :except => :destroy
  resources :provincias, :except => :destroy
  resources :departamentos, :except => :destroy
  resources :distritos, :except => :destroy
  resources :informes, :except => :destroy do
    get "informe_solicitado", on: :collection, as: :render_informe_default, action: :render_informe
  end
  resources :addendas, :except => :destroy
  resources :addendas_sumar, :except => :destroy do
    get 'new_masivo', :on => :collection, :as => :new_masivo
    post 'create_masivo', :on => :collection, :as => :create_masivo
  end
  resources :nomencladores, :except => :destroy do
    get 'asignar_precios', :on => :member, :as => :new_asignar_precios, :action => :new_asignar_precios
    get 'grupo_pdss/:grupo_pdss_id/asignar_precios', :on => :member, :as => :new_asignar_precios_por_grupo_pdss, :action => :new_asignar_precios_por_grupo_pdss
    put 'update_asignar_precios', :on => :member, :as => :update_asignar_precios, :action => :update_asignar_precios
  end
  resources :busqueda, :only => :index
  resources :verificador, :only => :index
  resources :padrones, :only => :index do
    post 'cierre', :on => :collection, :as => :cierre_de
  end
  resources :referentes, :except => [:index, :show, :destroy]
  resources :contactos#, :except => :destroy
  resources :liquidaciones, :except => :destroy
  resources :cuasi_facturas, :except => :destroy
  match "importar_detalle" => "cuasi_facturas#importar_detalle"
  match "importar_registros_de_prestaciones" => "cuasi_facturas#importar_registros_de_prestaciones"
  match "importar_archivo_p" => "liquidaciones#importar_archivo_p"
  match "procesar_bajas" => "novedades_de_los_afiliados#procesar_bajas"
  resources :novedades_de_los_afiliados, :except => [:new, :create] do
    get 'alta', :on => :collection, :as => :new_alta, :action => :new_alta
    get 'baja', :on => :collection, :as => :new_baja, :action => :new_baja
    get 'modificacion', :on => :collection, :as => :new_modificacion, :action => :new_modificacion
    post 'alta', :on => :collection, :as => :create_alta, :action => :create_alta
    post 'baja', :on => :collection, :as => :create_baja, :action => :create_baja
    post 'modificacion', :on => :collection, :as => :create_modificacion, :action => :create_modificacion
  end
  resources :afiliados, :only => [:show] do
    get :busqueda_por_aproximacion, on: :collection
    get 'prestaciones_brindadas', :on => :member, :as => :prestaciones_brindadas_al
  end
  resources :unidades_de_alta_de_datos, :except => :destroy
  resources :prestaciones_brindadas
  match "informe_de_beneficiarios_activos" => "informes#beneficiarios_activos"
  match "tablero_de_comandos_alto_impacto" => "informes#tablero_de_comandos_alto_impacto"
  resources :procesos_de_datos_externos, :except => :destroy do
    member do
      post 'aplicar', :as => :aplicar, :action => :aplicar
      post 'iniciar', :as => :iniciar, :action => :iniciar
    end
  end

  resources :prestaciones do
    get :validar_codigo , on: :collection
    get :edit_para_asignacion_de_precios, on: :member
  end
 
  resources :solicitudes_addendas, :except => :destroy
  

  root :to => 'inicio#index'


 

end

app/views/novedades_de_los_afiliados/_form_baja_masivo.html.haml
= form_for(@novedad, :url => @post_form_url) do |f|
  %div.hidden_field
    %input{ :id => "afiliado_id", :name => "afiliado_id", :type => "hidden", :value => @afiliado.afiliado_id }

  %h3 Tipo de solicitud
  %div.field_content
    %span.field_value Solicitud de baja de beneficiario

  %h3.header Clave única de beneficiario
  %div.field_content
    %span.field_value= @novedad.clave_de_beneficiario







  %h3 Fecha y centro inscriptor
  %div.field_content
    %span.field_name Fecha de solicitud de la baja
    %span.field_value= @novedad.fecha_de_la_novedad.strftime("%d/%m/%Y")
  - if @centros_de_inscripcion.size == 1
    %div.hidden_field
      %input{ :id => "novedad_del_afiliado_centro_de_inscripcion_id", :name => "novedad_del_afiliado[centro_de_inscripcion_id]", |
        :type => "hidden", :value => @centros_de_inscripcion[0][1] } |
    %div.field_content
      %span.field_name Centro de inscripción
      %span.field_value= @centros_de_inscripcion[0][0]
  - else
    %div.field
      = f.label :centro_de_inscripcion_id, "Centro de inscripción*"
      = f.select :centro_de_inscripcion_id, options_for_select(@centros_de_inscripcion, @novedad.centro_de_inscripcion_id), |
        {:include_blank => true} |
  %div.field
    = f.label :nombre_del_agente_inscriptor
    = f.text_field :nombre_del_agente_inscriptor, :style => "text-transform: uppercase;"

  %h3.header-with-note Observaciones generales*
  %p.note Indique en forma obligatoria con el mayor detalle y claridad posible por qué motivos se solicita la baja
  %div.field
    = f.text_area :observaciones_generales, :size => "80x8"

  %div.actions
    - if @novedad.new_record?
      = f.submit "Crear la solicitud"
      = link_to "Cancelar", @afiliado
    - else
      = f.submit "Modificar la solicitud"
      = link_to "Cancelar", @novedad

app/views/novedades_de_los_afiliados/_form_modificacion.html.haml
= form_for(@novedad, :url => create_modificacion_novedades_de_los_afiliados_url) do |f|
  %div.hidden_field
    %input{ :id => "afiliado_id", :name => "afiliado_id", :type => "hidden", :value => @afiliado.id }

  %h3 Tipo de solicitud
  %div.field_content
    %span.field_value Solicitud de modificación de datos

  %h3.header-with-note Clave única de beneficiario
  %p.note La clave de beneficiario no se puede modificar
  %div.field_content
    %span.field_value= @afiliado.clave_de_beneficiario

  %h3 Datos personales
  %div.field
    = f.label :apellido, "Apellido*"
    = f.text_field :apellido, :style => "text-transform: uppercase;"
  %div.field
    = f.label :nombre, "Nombre*"
    = f.text_field :nombre, :style => "text-transform: uppercase;"
  - if @afiliado.clase_de_documento && @afiliado.clase_de_documento.codigo == "P"
    %div.field_content
      %span.field_name Clase de documento
      %span.field_value= @afiliado.clase_de_documento.nombre
  - else
    %div.field
      = f.label :clase_de_documento_id, "Clase de documento*"
      = f.select :clase_de_documento_id, options_for_select(@clases_de_documentos, @novedad.clase_de_documento_id), |
        {:include_blank => true} |
  %div.field
    = f.label :tipo_de_documento_id, "Tipo de documento*"
    = f.select :tipo_de_documento_id, options_for_select(@tipos_de_documentos, @novedad.tipo_de_documento_id), |
      {:include_blank => true} |
  %div.field
    = f.label :numero_de_documento, "Número de documento*"
    = f.text_field :numero_de_documento, :style => "text-transform: uppercase;"
  %div.field
    = f.label :numero_de_celular
    = f.text_field :numero_de_celular
  %div.field
    = f.label :e_mail
    = f.email_field :e_mail

  %h3 Datos de nacimiento, sexo, origen y estudios
  %div.field
    = f.label :sexo_id, "Sexo*"
    = f.select :sexo_id, options_for_select(@sexos, @novedad.sexo_id), |
      {:inculde_blank => true} |
  %div.field
    = f.label :fecha_de_nacimiento, "Fecha de nacimiento*"
    = f.date_select :fecha_de_nacimiento, {:start_year => 1936, :end_year => Date.today.year, |
      :include_blank => true} |
  %div.field
    = f.label :es_menor, :title => "Marcar esta opción si a la fecha de inscripción o modificación aún no cumple los " + |
      Parametro.valor_del_parametro(:edad_limite_para_exigir_adulto_responsable).to_s + " años." |
    -
    = f.check_box :es_menor, :title => "Marcar esta opción si a la fecha de inscripción o modificación aún no cumple los " + |
      Parametro.valor_del_parametro(:edad_limite_para_exigir_adulto_responsable).to_s + " años." |
  %div.field
    = f.label :pais_de_nacimiento_id
    = f.select :pais_de_nacimiento_id, options_for_select(@paises, @novedad.pais_de_nacimiento_id), |
      {:include_blank => true} |
  %div.field
    = f.label :se_declara_indigena
    = f.check_box :se_declara_indigena
  #originarios
    %div.field
      = f.label :lengua_originaria_id
      = f.select :lengua_originaria_id, |
        options_for_select(@lenguas_originarias, @novedad.lengua_originaria_id), |
        {:include_blank => true} |
    %div.field
      = f.label :tribu_originaria_id
      = f.select :tribu_originaria_id, |
        options_for_select(@tribus_originarias, @novedad.tribu_originaria_id), |
        {:include_blank => true} |
  %div.field
    = f.label :alfabetizacion_del_beneficiario_id
    = f.select :alfabetizacion_del_beneficiario_id, |
      options_for_select(@niveles_de_instruccion, @novedad.alfabetizacion_del_beneficiario_id), |
      {:include_blank => true} |
  #alfab_benef.field
    = f.label :alfab_beneficiario_anios_ultimo_nivel
    = f.number_field :alfab_beneficiario_anios_ultimo_nivel, :size => 3

  %h3.header-with-note Datos de domicilio
  %p.note Complete al menos la calle ó manzana, el número, el departamento y distrito de residencia
  %div.field
    = f.label :domicilio_calle
    = f.text_field :domicilio_calle, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_numero
    = f.text_field :domicilio_numero, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_piso
    = f.text_field :domicilio_piso, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_depto
    = f.text_field :domicilio_depto, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_manzana
    = f.text_field :domicilio_manzana, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_entre_calle_1
    = f.text_field :domicilio_entre_calle_1, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_entre_calle_2
    = f.text_field :domicilio_entre_calle_2, :style => "text-transform: uppercase;"
  %div.field
    = f.label :telefono
    = f.text_field :telefono, :style => "text-transform: uppercase;"
  %div.field
    = f.label :otro_telefono
    = f.text_field :otro_telefono, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_departamento_id, "Departamento*"
    = f.select :domicilio_departamento_id, options_for_select(@departamentos, @novedad.domicilio_departamento_id), |
      {:include_blank => true} |
  #select_distritos.field
    = f.label :domicilio_distrito_id, "Distrito*"
    = f.select :domicilio_distrito_id, options_for_select(@distritos, @novedad.domicilio_distrito_id), |
      {:include_blank => true} |
  %div.field
    = f.label :domicilio_barrio_o_paraje
    = f.text_field :domicilio_barrio_o_paraje, :style => "text-transform: uppercase;"
  %div.field
    = f.label :domicilio_codigo_postal
    = f.text_field :domicilio_codigo_postal, :style => "text-transform: uppercase;"
  %h4 Observaciones
  %div.field
    = f.text_area :observaciones, :size => "80x8"
  %h3 Lugar de atención habitual
  %div.field
    = f.select :lugar_de_atencion_habitual_id, options_for_select(@efectores, @novedad.lugar_de_atencion_habitual_id), |
      {:include_blank => true} |

  #es_menor
    %h3.header-with-note Datos del adulto responsable
    %p.note Debe completar todos los datos de al menos uno de los adultos responsables (madre, padre o tutor/tutora)

    %h4 Datos de la madre
    %div.field
      = f.label :apellido_de_la_madre
      = f.text_field :apellido_de_la_madre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :nombre_de_la_madre
      = f.text_field :nombre_de_la_madre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :tipo_de_documento_de_la_madre_id
      = f.select :tipo_de_documento_de_la_madre_id, |
        options_for_select(@tipos_de_documentos, @novedad.tipo_de_documento_de_la_madre_id), |
        {:include_blank => true} |
    %div.field
      = f.label :numero_de_documento_de_la_madre
      = f.text_field :numero_de_documento_de_la_madre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :alfabetizacion_de_la_madre_id
      = f.select :alfabetizacion_de_la_madre_id, |
        options_for_select(@niveles_de_instruccion, @novedad.alfabetizacion_de_la_madre_id), |
        {:include_blank => true} |
    #alfab_madre.field
      = f.label :alfab_madre_anios_ultimo_nivel
      = f.number_field :alfab_madre_anios_ultimo_nivel, :size => 3
    %h4 Datos del padre
    %div.field
      = f.label :apellido_del_padre
      = f.text_field :apellido_del_padre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :nombre_del_padre
      = f.text_field :nombre_del_padre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :tipo_de_documento_del_padre_id
      = f.select :tipo_de_documento_del_padre_id, |
        options_for_select(@tipos_de_documentos, @novedad.tipo_de_documento_del_padre_id), |
        {:include_blank => true} |
    %div.field
      = f.label :numero_de_documento_del_padre
      = f.text_field :numero_de_documento_del_padre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :alfabetizacion_del_padre_id
      = f.select :alfabetizacion_del_padre_id, |
        options_for_select(@niveles_de_instruccion, @novedad.alfabetizacion_del_padre_id), |
        {:include_blank => true} |
    #alfab_padre.field
      = f.label :alfab_padre_anios_ultimo_nivel
      = f.number_field :alfab_padre_anios_ultimo_nivel, :size => 3
    %h4 Datos de la tutora o tutor
    %div.field
      = f.label :apellido_del_tutor
      = f.text_field :apellido_del_tutor, :style => "text-transform: uppercase;"
    %div.field
      = f.label :nombre_del_tutor
      = f.text_field :nombre_del_tutor, :style => "text-transform: uppercase;"
    %div.field
      = f.label :tipo_de_documento_del_tutor_id
      = f.select :tipo_de_documento_del_tutor_id, |
        options_for_select(@tipos_de_documentos, @novedad.tipo_de_documento_del_tutor_id), |
        {:include_blank => true} |
    %div.field
      = f.label :numero_de_documento_del_tutor
      = f.text_field :numero_de_documento_del_tutor, |
        :style => "text-transform: uppercase;" |
    %div.field
      = f.label :alfabetizacion_del_tutor_id
      = f.select :alfabetizacion_del_tutor_id, |
        options_for_select(@niveles_de_instruccion, @novedad.alfabetizacion_del_tutor_id), |
        {:include_blank => true} |
    #alfab_tutor.field
      = f.label :alfab_tutor_anios_ultimo_nivel
      = f.number_field :alfab_tutor_anios_ultimo_nivel, :size => 3

  #embarazo
    %h3 Datos del embarazo
    %div.field
      = f.label :esta_embarazada, :title => "Marcar esta opción si a la fecha de inscripción o modificación cursaba un embarazo."
      = f.check_box :esta_embarazada, |
        :title => "Marcar esta opción si a la fecha de inscripción o modificación cursaba un embarazo." |
    #esta_embarazada
      %div.field
        = f.label :fecha_de_la_ultima_menstruacion
        = f.date_select :fecha_de_la_ultima_menstruacion, {:start_year => 2001, :end_year => Date.today.year, |
          :include_blank => true} |
      %div.field
        = f.label :fecha_de_diagnostico_del_embarazo
        = f.date_select :fecha_de_diagnostico_del_embarazo, {:start_year => 2001, :end_year => Date.today.year, |
          :include_blank => true} |
      %div.field
        = f.label :semanas_de_embarazo
        = f.number_field :semanas_de_embarazo, :size => 3
      %div.field
        = f.label :fecha_probable_de_parto
        = f.date_select :fecha_probable_de_parto, {:start_year => 2001, :end_year => Date.today.year + 1, :include_blank => true}

  %h3 Remediar+Redes
  %div.field
    = f.label :score_de_riesgo
    = f.number_field :score_de_riesgo, :size => 3

  %h3 Discapacidad
  %div.field
    = f.label :discapacidad_id
    = f.select :discapacidad_id, options_for_select(@discapacidades, @novedad.discapacidad_id), {:include_blank => true}

  %h3 Fecha y centro inscriptor
  %div.field
    = f.label :fecha_de_la_novedad
    = f.date_select :fecha_de_la_novedad, {:start_year => Date.today.year - 1, :end_year => Date.today.year, |
      :include_blank => true} |
  %div.field
    = f.label :centro_de_inscripcion_id
    = f.select :centro_de_inscripcion_id, options_for_select(@centros_de_inscripcion, @novedad.centro_de_inscripcion_id), |
      {:include_blank => true} |
  %div.field
    = f.label :nombre_del_agente_inscriptor
    = f.text_field :nombre_del_agente_inscriptor, :style => "text-transform: uppercase;"

  %h3 Observaciones generales
  %div.field
    = f.text_area :observaciones_generales, :size => "80x8"

  %div.actions
    - if @novedad.new_record?
      = f.submit "Crear la solicitud"
      = link_to "Cancelar", @afiliado
    - else
      = f.submit "Modificar la solicitud"
      = link_to "Cancelar", @novedad

app/views/novedades_de_los_afiliados/edit.html.haml
- content_for :title do
  Modificación de datos de la solicitud

- content_for :other_includes do
  = javascript_include_tag "novedades_de_los_afiliados"

#content-header
  %h1 Modificación de datos de la solicitud

= render :partial => "shared/info", :locals => { :registro => @novedad }

#content-body
  %h2.first-header-with-note Formulario de modificación de datos de la solicitud
  %p.note Los campos marcados con asterisco (*) son obligatorios

  - if @novedad.tipo_de_novedad.codigo == "B"
    = render "form_baja"
  - else
    = render "form"

app/views/novedades_de_los_afiliados/new.html.haml
- content_for :title do
  Creación de una nueva solicitud

- content_for :other_includes do
  = javascript_include_tag "novedades_de_los_afiliados"

#content-header
  %h1 Creación de una nueva solicitud

= render :partial => "shared/info", :locals => { :registro => @novedad }

#content-body
  %h2.first-header-with-note Formulario de creación de una nueva solicitud
  %p.note Los campos marcados con asterisco (*) son obligatorios

  - if @novedad.tipo_de_novedad.codigo == "B"
    = render "form_baja"
  - else
    = render "form"

app/views/novedades_de_los_afiliados/show.html.haml
- content_for :title do
  Detalle de la solicitud

#content-header
  %h1 Detalle de la solicitud
  #action-links
    - if can?(:update, @novedad) && @novedad.pendiente?
      = link_to "Modificar la solicitud", edit_novedad_del_afiliado_path(@novedad)
      = link_to "Anular la solicitud", @novedad, :method => :delete, |
        :confirm => "¿Está seguro que desea anular esta solicitud?\nEsta acción no se podrá deshacer." |

    - # TODO: Verificar si la UAD actual tiene activado el módulo para registrar prestaciones
    - if can?(:create, PrestacionBrindada) && @novedad.tipo_de_novedad.codigo != "B" |
      && ["R", "P"].member?(@novedad.estado_de_la_novedad.codigo) |
      -
      = link_to("Registrar prestación", |
        new_prestacion_brindada_path(:clave_de_beneficiario => @novedad.clave_de_beneficiario)) |
    - if can?(:read, VistaGlobalDePrestacionBrindada) && current_user.in_group?(:operaciones)
      = link_to("Historial de prestaciones", prestaciones_brindadas_al_afiliado_path)
    - elsif can?(:read, PrestacionBrindada) && current_user.in_group?(:facturacion_uad)
      = link_to("Historial de prestaciones", |
        prestaciones_brindadas_path(:clave_de_beneficiario => @novedad.clave_de_beneficiario)) |

= render :partial => "shared/info", :locals => { :registro => @novedad }

#content-body
  %h2.first-header Información de la solicitud registrada

  - case
    - when @novedad.tipo_de_novedad.codigo == "A"
      = render :partial => "show_alta"
    - when @novedad.tipo_de_novedad.codigo == "B"
      = render :partial => "show_baja"
    - when @novedad.tipo_de_novedad.codigo == "M"
      = render :partial => "show_modificacion"

app/views/novedades_de_los_afiliados/verificacion.html.haml
- content_for :title do
  Verificación preliminar de datos para la creación de una solicitud de alta de beneficiario

- content_for :other_includes do
  = javascript_include_tag 'verificacion'

#content-header
  %h1 Verificación preliminar de datos para la creación de una solicitud de alta de beneficiario

= render :partial => "shared/info", :locals => { :registro => @novedad }

#content-body
  %h2.first-header-with-note Formulario de verificación preliminar de datos
  %p.note Los campos marcados con asterisco (*) son obligatorios

  = form_for(@novedad, :url => create_alta_novedades_de_los_afiliados_url, :method => :get) do |f|
    %h3 Información preliminar para la verificación
    %div.field
      = f.label :apellido, "Apellido*"
      = f.text_field :apellido, :style => "text-transform: uppercase;"
    %div.field
      = f.label :nombre, "Nombre*"
      = f.text_field :nombre, :style => "text-transform: uppercase;"
    %div.field
      = f.label :clase_de_documento_id, "Clase de documento*"
      = f.select :clase_de_documento_id, options_for_select(@clases_de_documentos, @novedad.clase_de_documento_id)
    %div.field
      = f.label :tipo_de_documento_id, "Tipo de documento*"
      = f.select :tipo_de_documento_id, options_for_select(@tipos_de_documentos, @novedad.tipo_de_documento_id)
    %div.field
      = f.label :numero_de_documento, "Número de documento*"
      = f.text_field :numero_de_documento, :style => "text-transform: uppercase;"
    %div.field
      = f.label :fecha_de_nacimiento, "Fecha de nacimiento*"
      = f.date_select :fecha_de_nacimiento, {:start_year => 1936, :end_year => Date.today.year, |
        :include_blank => true} |
    %div.field
      = f.label :numero_de_documento_de_la_madre
      = f.text_field :numero_de_documento_de_la_madre, :placeholder => "Solo si dispone del dato y es un menor"

    %div.actions
      = f.submit "Verificar"
      = link_to "Cancelar", root_url